#!/bin/bash

if [ -z "$(nmap 127.0.0.1 -p 80|grep open)" ]; then
        echo "no esta Corriendo"
	fuser -k 80/tcp
	fuser -k 80/tcp
        cd /home/idcadmin/sistemaFacturacion/facture
        python manage.py runserver 10.0.10.100:80
else
        echo "Esta corriendo"
fi

